ALL: lib

CFLAGS   = 
FFLAGS   = 
SOURCEC  = 
SOURCECU = matstructgridgpu.cu
SOURCEF  = 
SOURCEH  = matstructgridgpu.h
OBJSC    = matstructgridgpu.o
OBJSF    = 
LIBBASE  = libpetscmat
DIRS     = 
MANSEC   = Mat
LOCDIR   = src/mat/impls/structgrid/structgridgpu

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
