
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = polynomial.c
SOURCEF  =
SOURCEH  = polynomial.h
OBJSC    = polynomial.o
OBJSF    =
LIBBASE  = libpetscksp
DIRS     = 
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/polynomial/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
