ALL: lib

CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = swarmcreate.c swarm.c
SOURCEF  =
SOURCEH  =
DIRS     = examples
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMSWARM
LOCDIR   = src/dm/impls/swarm/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
