ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCECU = sggpu.cu sggpufact.cu
SOURCEF  =
SOURCEH  = sggpu.h
OBJSC    = sggpu.o sggpufact.o
OBJSF    =
LIBBASE  = libpetscmat
DIRS     =
MANSEC   = Mat
LOCDIR   = src/mat/impls/sggpu/seq/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
