
ALL: lib

CFLAGS   = -mavx -fopenmp
FFLAGS   =
SOURCEC  = matbsgmpi.c 
SOURCEF  = 
SOURCEH  = matbsgmpi.h
OBJSC    = matbsgmpi.o
OBJSF    = 
LIBBASE  = libpetscmat
DIRS     = 
MANSEC   = Mat
DIRS     =
LOCDIR   = src/mat/impls/blockstructgrid/mpi

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
