
ALL: lib

CFLAGS   = -mavx -ggdb #-g -Wa,-alhd 
FFLAGS   =
SOURCEC  = matblockstructgrid.c matmultbintrinsics.c
SOURCEF  = 
SOURCEH  = matblockstructgrid.h
OBJSC    = matblockstructgrid.o matmultbintrinsics.o
OBJSF    = 
LIBBASE  = libpetscmat
DIRS     = 
MANSEC   = Mat
DIRS     =
LOCDIR   = src/mat/impls/blockstructgrid

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
