
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = matstructgrid.c matmultintrinsics.c matmulopenmp.c
SOURCEF  = 
SOURCEH  = matstructgrid.h
OBJSC    = matstructgrid.o matmultintrinsics.o matmulopenmp.o
OBJSF    = 
LIBBASE  = libpetscmat
DIRS     = 
MANSEC   = Mat
DIRS     = structgridgpu
LOCDIR   = src/mat/impls/structgrid

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
