ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mpisggpu.c
SOURCECU =
SOURCEF  =
SOURCEH  = mpisggpu.h
OBJSC    = mpisggpu.o
OBJSF    =
LIBBASE  = libpetscmat
DIRS     =
MANSEC   = Mat
LOCDIR   = src/mat/impls/sggpu/mpi/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
